-- Migration Patients — La Vita Per Te
-- Schéma dédié + table dossiers (reprise fidèle des 146 champs FileMaker,
-- tout en text pour l'import ; typage affiné ensuite par vues).
-- À exécuter dans Supabase : SQL Editor → New query → coller → Run.

create schema if not exists patients;

create table if not exists patients.dossiers (
  id bigint generated always as identity primary key,
  fmp_row integer,
  nom_prenom text,
  date_de_naissance text,
  adresse text,
  tel text,
  statut text,
  rubrique_7 text,
  enfants text,
  tabac text,
  alcool text,
  regles text,
  doul_post_coit text,
  age_menarche text,
  rs text,
  mst text,
  contraception text,
  partenaires text,
  pap text,
  hpv text,
  mamo text,
  echographies text,
  colposcopies text,
  renseignements_cliniques text,
  resultat text,
  commentaires text,
  csb text,
  date text,
  a_revoir text,
  total_pap text,
  pap_decompte_2 text,
  hpv_decompte text,
  n_patiente text,
  resultat_histologique text,
  type_d_intervention_1 text,
  type_d_intervention_2 text,
  resultat_histologique_2 text,
  resultat_pap_1 text,
  resultat_pap_2 text,
  resultat_pap_3 text,
  n_de_lame_1 text,
  n_de_lame_2 text,
  n_de_lame_3 text,
  date_pap text,
  date_2 text,
  date_3 text,
  grossesses text,
  date_dernieres_regles text,
  parites text,
  avortements text,
  menopause text,
  date_hpv text,
  prelevement text,
  centre_prelev text,
  nom_du_medecin text,
  date_colpo text,
  colposcopie text,
  resultat_colpo text,
  gsc text,
  biopsie text,
  resultat_histologique_colpo1 text,
  resultat_histologique_colpo2 text,
  resultat_histologique_colpo3 text,
  curetage_endocervical text,
  date_intervention text,
  type_d_intervention text,
  resultat_histo_intervention text,
  consultation text,
  facteurs_associes text,
  mois_annee text,
  pap_satisfaisant_1 text,
  pap_satisfaisant_2 text,
  pap_satisfaisant_3 text,
  connu_par text,
  colpo_satifaisante text,
  colpo_non_satifaisante text,
  epithelium_original text,
  epithelium_cylindrique_visible_pour text,
  zone_de_transformation_normale_ntz text,
  antz_grade_1 text,
  antz_grade_2 text,
  observation_a_l_exterieur_de_la_zone_de_transformation text,
  suspicion_de_condylomatose text,
  autres_observations text,
  test_de_schiller text,
  nombre_de_biopsies_prelevees text,
  observations_colpo text,
  date_mamo text,
  compte_rendu_mamo text,
  age text,
  csb_decompte text,
  csb_patiente text,
  csb_decompte_cumule text,
  nom_prenom_decompte_cumule text,
  total_patiente text,
  commentaire_medecin text,
  prise_en_charge text,
  total_prise_en_charge text,
  mois_annee_decompte text,
  tranche_d_age text,
  tranche_d_age_decompte text,
  n_de_tube text,
  leucorrhees_actuelles text,
  prelevment_pap text,
  annee text,
  motif_derniere_intervention text,
  numero_code text,
  date_pap_precedent text,
  satisfaisant_oui_non text,
  diagnostic text,
  action_suivante text,
  notes_pap text,
  operatrice text,
  h text,
  h2 text,
  suspicion_de_neoplasie_invasive text,
  condylomatose text,
  etudes_primaires text,
  etudes_secondaires text,
  etudes_superieures text,
  emploi text,
  n_de_ref_prelevement text,
  sexe text,
  medecin_referent text,
  date_prelevement text,
  nature_du_prelevement text,
  organe text,
  diagnostic_presomptif text,
  fixateur text,
  specimen_recu_le text,
  ref_number text,
  snomed_t text,
  snomed_m text,
  description_macroscopique text,
  description_microscopique text,
  commentaire text,
  description text,
  nomprenom_enfant text,
  sonde_utilisee text,
  voie_d_abord text,
  mesure text,
  observations text,
  diagnostic_senologie text,
  cancer_famille text,
  c_1er_enfant_a text,
  c_1er_allaitement_a text,
  chirurgie_sein text,
  consulte_par text,
  imported_at timestamptz not null default now()
);

-- Index de recherche courants
create index if not exists dossiers_nom_idx on patients.dossiers (nom_prenom);
create index if not exists dossiers_num_idx on patients.dossiers (n_patiente);

-- Sécurité : RLS actif, aucune policy = aucun accès anon/authenticated.
-- Seul le serveur (service_role, qui bypasse RLS) lit/écrit.
alter table patients.dossiers enable row level security;

grant usage on schema patients to service_role;
grant all on all tables in schema patients to service_role;
alter default privileges in schema patients grant all on tables to service_role;

-- Journal d'accès applicatif (qui a consulté quel dossier)
create table if not exists patients.acces_log (
  id bigint generated always as identity primary key,
  ts timestamptz not null default now(),
  user_email text not null,
  action text not null,
  dossier_id bigint,
  details text
);
alter table patients.acces_log enable row level security;
